services:
  db:
    image: postgres:15
    container_name: ruangketiga_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ruangketiga
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: ruangketiga_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: ruangketiga
    ports:
      - "8080:8080"

  migrate:
    image: migrate/migrate:latest
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://myuser:mypassword@db:5432/ruangketiga?sslmode=disable",
      "up"
    ]

volumes:
  dbdata:
